### ISSUE TITLE
Fugu15 Max

### ISSUE THREAD

**Issue by botmaker69** [Paisseon/paisseon.github.io#2]
Repo needs iphoneos-arm64

Also does satella work on fugu 15 max?

**Comment by Paisseon** [comment]
I am working on adding rootless support (including Fugu15) but it's in testing rn

**Comment by botmaker69** [comment]
bet

**Comment by Paisseon** [comment]
Took forever but several of my tweaks are now updated :)

**Comment by botmaker69** [comment]
Ye I saw, awesome! Thanks for all u do haha love having a good iap cracker
